version: '3.8'

services:
  web:
    build: ./backend/TaskTracker
    command: bash -c 'while !</dev/tcp/db/5432; do sleep 1; done; uvicorn app.main:app --host 0.0.0.0'
    volumes:
      - .:/backend/TaskTracker/app
    ports:
      - "8008:8008"
    environment:
      - DATABASE_URL=postgresql://fastapi_traefik:fastapi_traefik@db:5432/fastapi_traefik
      - SECRET_KEY=2f92041b9c778316ebbaf5e639c19d1088e6372f8904728eaa1f79a30cd05e2e
      - ALGORITHM=HS256
    depends_on:
      - db

  db:
    image: postgres:15-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    expose:
      - 5432
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=fastapi_traefik
      - POSTGRES_PASSWORD=fastapi_traefik
      - POSTGRES_DB=fastapi_traefik

  pgadmin:
    container_name: pgadmin4_container_1
    image: dpage/pgadmin4:7
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
      PGADMIN_LISTEN_PORT: 5050
    ports:
      - "5050:5050"
    volumes:
      - pgadmin-data:/var/lib/pgadmin

  client:
    build: ./frontend/task-tracker
    command: yarn start
    volumes:
      - .:/frontend/task-tracker/app
    ports:
      - "80:80"
    depends_on:
      - web
    environment:
      - PORT=80

volumes:
  postgres_data:
  pgadmin-data:
